# Generated by Django 5.0.3 on 2024-05-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                max_length=6,
                null=True,
            ),
        ),
    ]
