# Generated by Django 4.2.13 on 2024-05-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_product_remove_subcategory_sub_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("status", "-activate_date")},
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                default="static/product_images/logo.jpg",
                upload_to="static/product_images/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="home.category",
            ),
        ),
    ]
