# Generated by Django 4.2.13 on 2024-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_product_options_alter_category_category_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="sub_category",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                default="static/product_images/no_image.jpg",
                upload_to="static/product_images/",
            ),
        ),
    ]
