# Generated by Django 4.2.13 on 2024-05-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_rename_sub_category_category_parent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_image",
            new_name="image",
        ),
    ]
