# Generated by Django 4.2.13 on 2024-05-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_category_image_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="image",
            new_name="category_image",
        ),
    ]
