# Generated by Django 4.2.13 on 2024-05-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_productcart_alter_cartitem_product_delete_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductCart",
        ),
    ]
